---
- name: Install httpd.
  yum:
    name: httpd
    state: latest
  become: true
- name: Ensure httpd is running (and enable it at boot).
  service:
    name: httpd
    state: started
    enabled: true
  become: true
